import XCTest

@testable import Sentori

/// This transport and the TypeScript kernel must count the same way.
///
/// `droppedEvents` is the one number that tells a reader "you are not
/// seeing everything". If it means one thing on iOS and another in the
/// browser it stops being readable, and there is no way to notice: a
/// count that is too low looks exactly like a quiet period.
///
/// The vectors are generated by `sdk/core/src/transport.ts` itself
/// (`scripts/gen-transport-vectors.mjs`), so this asserts against what
/// the other implementations do rather than against what this file's
/// author believed they do.
final class SentoriTransportVectorsTests: XCTestCase {

    private struct Op: Decodable {
        let op: String
        let n: Int?
        let name: String?
        let ok: Bool?
        let release: String?
    }
    private struct Stat: Decodable {
        let name: String
        let release: String
        let passDelta: Int
        let failDelta: Int
    }
    private struct Expect: Decodable {
        let queued: Int
        let dropped: Int
        let sessions: Int
        let assertStats: [Stat]
    }
    private struct Vector: Decodable {
        let name: String
        let applies: [String]
        let ops: [Op]
        let expect: Expect
    }
    private struct Fixture: Decodable {
        let vectors: [Vector]
    }

    private func loadVectors() throws -> [Vector] {
        // Two layouts, for the same reason the identity vectors have
        // two: in the monorepo the fixtures are shared with Android
        // four levels up, and in the published mirror the package is
        // the repository.
        var dir = URL(fileURLWithPath: #filePath).deletingLastPathComponent()
        for _ in 0..<6 {
            let candidate = dir.appendingPathComponent("fixtures/transport-vectors.json")
            if FileManager.default.fileExists(atPath: candidate.path) {
                let data = try Data(contentsOf: candidate)
                return try JSONDecoder().decode(Fixture.self, from: data).vectors
            }
            dir = dir.deletingLastPathComponent()
        }
        // Not a skip. A missing fixture means the cross-language gate
        // is not running, and a gate that quietly stops running is the
        // failure it exists to prevent.
        XCTFail("transport-vectors.json is not above \(#filePath) — the mirror did not carry it")
        return []
    }

    func testCountsTheSameWayTheKernelDoes() throws {
        let vectors = try loadVectors()
        XCTAssertGreaterThanOrEqual(
            vectors.count, 5,
            "fixture looks truncated — a file that reads as empty passes everything"
        )

        var ran = 0
        for v in vectors where v.applies.contains("swift") {
            ran += 1
            SentoriTransport.__resetForTests()

            var counter = 0
            for op in v.ops {
                switch op.op {
                case "enqueue":
                    for _ in 0..<(op.n ?? 0) {
                        SentoriTransport.enqueue(["id": "e\(counter)", "kind": "error"])
                        counter += 1
                    }
                case "assert":
                    SentoriTransport.countAssert(
                        name: op.name ?? "",
                        ok: op.ok ?? true,
                        release: op.release ?? "vectors@1.0.0"
                    )
                default:
                    // `session` never appears with `swift` in
                    // `applies`; reaching this means the fixture grew a
                    // case this transport has no answer for, and
                    // ignoring it quietly is how a gate stops covering
                    // what it names.
                    XCTFail("\(v.name): unknown op \(op.op)")
                }
            }

            XCTAssertEqual(
                SentoriTransport.__peekQueue().count, v.expect.queued,
                "\(v.name) — queued"
            )
            XCTAssertEqual(
                SentoriTransport.__peekDropped(), v.expect.dropped,
                "\(v.name) — dropped"
            )

            let got = SentoriTransport.__peekAssertStats().sorted {
                let l = "\($0["name"] ?? "")\($0["release"] ?? "")"
                let r = "\($1["name"] ?? "")\($1["release"] ?? "")"
                return l < r
            }
            XCTAssertEqual(got.count, v.expect.assertStats.count, "\(v.name) — assert stat rows")
            for (i, want) in v.expect.assertStats.enumerated() where i < got.count {
                XCTAssertEqual(got[i]["name"] as? String, want.name, "\(v.name) — stat \(i) name")
                XCTAssertEqual(
                    got[i]["release"] as? String, want.release, "\(v.name) — stat \(i) release")
                XCTAssertEqual(
                    got[i]["passDelta"] as? Int, want.passDelta, "\(v.name) — stat \(i) passDelta")
                XCTAssertEqual(
                    (got[i]["failDelta"] as? Int) ?? 0, want.failDelta,
                    "\(v.name) — stat \(i) failDelta")
            }
        }

        // The fixture says which implementations each case binds. If
        // none bound this one, the loop above asserted nothing.
        XCTAssertGreaterThanOrEqual(ran, 4, "no vector applied to swift — this test ran nothing")
    }
}
