import XCTest

@testable import Sentori

/// The ring against the TypeScript one, frame for frame.
///
/// The vectors are generated by `scripts/gen-replay-vectors.mjs` from
/// `sdk/core/src/replay-ring.ts`, which is the source of truth for
/// what a replay is. Three implementations that disagree produce a
/// replay of a screen the user never saw, and the player renders a
/// wrong frame without complaint — so nothing but this says they
/// agree.
final class SentoriReplayRingTests: XCTestCase {

    private func loadVectors() throws -> [[String: Any]] {
        // Two layouts, because this package lives in two places: the
        // monorepo, where the fixtures are shared with Android, and
        // the published mirror, where the package is the repository.
        var dir = URL(fileURLWithPath: #filePath).deletingLastPathComponent()
        for _ in 0..<6 {
            let candidate = dir.appendingPathComponent("fixtures/replay-vectors.json")
            if FileManager.default.fileExists(atPath: candidate.path) {
                let data = try Data(contentsOf: candidate)
                return try JSONSerialization.jsonObject(with: data) as? [[String: Any]] ?? []
            }
            dir = dir.deletingLastPathComponent()
        }
        // Not a skip. A missing fixture means the cross-language gate
        // is not running, and a gate that quietly stops running is the
        // failure it exists to prevent.
        XCTFail("replay-vectors.json is not above \(#filePath) — the mirror did not carry it")
        return []
    }

    private func node(_ raw: [String: Any]) -> SentoriReplay.Node {
        SentoriReplay.Node(
            x: raw["x"] as? Double ?? 0,
            y: raw["y"] as? Double ?? 0,
            w: raw["w"] as? Double ?? 0,
            h: raw["h"] as? Double ?? 0,
            kind: raw["kind"] as? String,
            text: raw["text"] as? String,
            color: raw["color"] as? String
        )
    }

    func testMatchesTheTypeScriptRing() throws {
        let vectors = try loadVectors()
        XCTAssertGreaterThanOrEqual(
            vectors.count, 10,
            "the fixture looks truncated — a file that reads as empty passes everything"
        )

        for vector in vectors {
            let name = vector["name"] as? String ?? "?"
            let options = vector["options"] as? [String: Any] ?? [:]
            let ring = SentoriReplay.Ring(
                keyframeMs: options["keyframeMs"] as? Double ?? 4000,
                windowMs: options["windowMs"] as? Double ?? 60000,
                maxItems: options["maxItems"] as? Int ?? 1000
            )

            let frames = vector["frames"] as? [[String: Any]] ?? []
            let expectedEmitted = vector["emitted"] as? [Any] ?? []
            XCTAssertEqual(frames.count, expectedEmitted.count, "\(name): fixture is malformed")

            for (index, raw) in frames.enumerated() {
                let frame = SentoriReplay.Frame(
                    ts: raw["ts"] as? Double ?? 0,
                    width: raw["width"] as? Double ?? 0,
                    height: raw["height"] as? Double ?? 0,
                    nodes: (raw["nodes"] as? [[String: Any]] ?? []).map(node)
                )
                let got = ring.push(frame)
                let want = expectedEmitted[index]
                if want is NSNull {
                    XCTAssertNil(got, "\(name): frame \(index) should have emitted nothing")
                } else {
                    guard let got else {
                        XCTFail("\(name): frame \(index) emitted nothing, expected an entry")
                        continue
                    }
                    assertSame(got, want as? [String: Any] ?? [:], "\(name) frame \(index)")
                }
            }

            let expectedRing = vector["ring"] as? [[String: Any]] ?? []
            let gotRing = ring.snapshot()
            XCTAssertEqual(gotRing.count, expectedRing.count, "\(name): ring size")
            for (index, want) in expectedRing.enumerated() where index < gotRing.count {
                assertSame(gotRing[index], want, "\(name) ring[\(index)]")
            }
        }
    }

    /// Structural, not textual. Key order differs between a JS object
    /// literal and a Swift dictionary, and the player parses — pinning
    /// byte equality would pin something that does not matter and
    /// cannot be held.
    private func assertSame(_ got: Any, _ want: Any, _ path: String) {
        switch (got, want) {
        case let (g as [String: Any], w as [String: Any]):
            XCTAssertEqual(
                Set(g.keys), Set(w.keys),
                "\(path): keys differ — got \(Set(g.keys).sorted()), want \(Set(w.keys).sorted())"
            )
            for key in w.keys where g[key] != nil {
                assertSame(g[key]!, w[key]!, "\(path).\(key)")
            }
        case let (g as [Any], w as [Any]):
            XCTAssertEqual(g.count, w.count, "\(path): length")
            for (index, item) in w.enumerated() where index < g.count {
                assertSame(g[index], item, "\(path)[\(index)]")
            }
        default:
            let g = (got as? NSNumber).map { $0.doubleValue.description } ?? String(describing: got)
            let w = (want as? NSNumber).map { $0.doubleValue.description } ?? String(describing: want)
            XCTAssertEqual(g, w, "\(path)")
        }
    }

    func testTwoLayersWithTheSameGeometryStayTwoNodes() {
        // A page root and the fullscreen overlay covering it share
        // x/y/w/h. Keying on geometry alone collapsed them, and the
        // replay drew the page through the overlay.
        let nodes = [
            SentoriReplay.Node(x: 0, y: 0, w: 320, h: 640, kind: "view", text: nil, color: nil),
            SentoriReplay.Node(x: 0, y: 0, w: 320, h: 640, kind: "overlay", text: nil, color: nil),
        ]
        let keys = SentoriReplay.index(nodes).map(\.key)
        XCTAssertEqual(keys, ["0,0,320,640#0", "0,0,320,640#1"])
    }

    func testSubPixelJitterIsNotAChange() {
        let a = SentoriReplay.Node(x: 0.2, y: 0.4, w: 10.6, h: 10.9, kind: "a", text: nil, color: nil)
        let b = SentoriReplay.Node(x: 0.7, y: 0.1, w: 10.2, h: 10.4, kind: "a", text: nil, color: nil)
        XCTAssertEqual(
            SentoriReplay.nodeKey(a, occurrence: 0), SentoriReplay.nodeKey(b, occurrence: 0)
        )
    }
}
