import Foundation

/// The last sixty seconds of what the screen looked like.
///
/// The wireframe capture has been on both native platforms for a
/// while; the ring that decides what to keep of it lived only in the
/// React Native package, so a native-only app captured nothing. This
/// is the port, and it is checked frame for frame against vectors
/// generated by `sdk/core/src/replay-ring.ts` — three implementations
/// of a diff that disagree produce a replay of a screen the user
/// never saw, and the player renders a wrong frame without complaint.
///
/// The caller owns the timer. It must not be the main thread: the
/// wireframe capture dispatches to main internally, so a timer on
/// main deadlocks on its own capture.
enum SentoriReplay {
    struct Node: Codable, Equatable {
        var x: Double
        var y: Double
        var w: Double
        var h: Double
        var kind: String?
        var text: String?
        var color: String?
    }

    struct Frame {
        var ts: Double
        var width: Double
        var height: Double
        var nodes: [Node]
    }

    /// Identity is geometry plus occurrence index in walk order.
    ///
    /// Geometry alone is not identity: a page root and the fullscreen
    /// overlay covering it share x/y/w/h, and keying on that
    /// collapsed them into one node — the overlay inherited the
    /// root's z-position and the replay drew the page *through* it.
    ///
    /// Truncated to integers first, because sub-pixel jitter from a
    /// layout pass that returns floats would make every node new on
    /// every tick, turning a still screen into a stream of full
    /// deltas.
    static func nodeKey(_ node: Node, occurrence: Int) -> String {
        "\(Int(node.x)),\(Int(node.y)),\(Int(node.w)),\(Int(node.h))#\(occurrence)"
    }

    /// Ordered, because a delta's arrays are compared against the
    /// TypeScript ring's and a dictionary would shuffle them.
    static func index(_ nodes: [Node]) -> [(key: String, node: Node, at: Int)] {
        var seen: [String: Int] = [:]
        var out: [(key: String, node: Node, at: Int)] = []
        for (at, node) in nodes.enumerated() {
            let base = nodeKey(node, occurrence: 0).components(separatedBy: "#")[0]
            let occurrence = seen[base] ?? 0
            seen[base] = occurrence + 1
            out.append((key: "\(base)#\(occurrence)", node: node, at: at))
        }
        return out
    }

    struct Delta {
        var added: [(node: Node, at: Int, id: String)] = []
        var changed: [(node: Node, id: String)] = []
        var removed: [(node: Node, id: String)] = []

        var count: Int { added.count + changed.count + removed.count }
    }

    /// Position is identity, so a node that moved is a removal and an
    /// addition rather than a change. Only what a wireframe draws —
    /// kind, colour, text — makes an existing node different.
    static func delta(
        from previous: [(key: String, node: Node, at: Int)],
        to current: [(key: String, node: Node, at: Int)]
    ) -> Delta {
        var before: [String: Node] = [:]
        for entry in previous { before[entry.key] = entry.node }
        var now: Set<String> = []
        for entry in current { now.insert(entry.key) }

        var out = Delta()
        for entry in current {
            guard let was = before[entry.key] else {
                out.added.append((node: entry.node, at: entry.at, id: entry.key))
                continue
            }
            if (was.kind ?? "") != (entry.node.kind ?? "")
                || (was.color ?? "") != (entry.node.color ?? "")
                || (was.text ?? "") != (entry.node.text ?? "")
            {
                out.changed.append((node: entry.node, id: entry.key))
            }
        }
        for entry in previous where !now.contains(entry.key) {
            out.removed.append((node: entry.node, id: entry.key))
        }
        return out
    }

    /// Past this share of the screen changing, a delta is a
    /// near-rewrite and a keyframe reconstructs more cheaply.
    static let deltaToKeyframeRatio = 0.4

    /// Below this many nodes the ratio is noise — two rectangles
    /// moving on a three-node screen is not a screen transition.
    static let keyframeRatioMinNodes = 10

    final class Ring {
        private var entries: [[String: Any]] = []
        private var lastState: [(key: String, node: Node, at: Int)]?
        private var lastKeyframeTs: Double = 0
        private let keyframeMs: Double
        private let windowMs: Double
        private let maxItems: Int
        private let lock = NSLock()

        init(keyframeMs: Double = 4000, windowMs: Double = 60000, maxItems: Int = 1000) {
            self.keyframeMs = keyframeMs
            self.windowMs = windowMs
            self.maxItems = maxItems
        }

        /// Take a frame. Returns what was appended, or `nil` when the
        /// frame was identical to the last — a heartbeat with nothing
        /// in it is dropped, because a minute of a still screen should
        /// not cost 120 entries that reconstruct to the same picture.
        @discardableResult
        func push(_ frame: Frame) -> [String: Any]? {
            lock.lock()
            defer { lock.unlock() }

            let state = index(frame.nodes)
            let cold = lastState == nil
            let overdue = frame.ts - lastKeyframeTs >= keyframeMs

            var entry: [String: Any]
            if cold || overdue {
                entry = keyframe(frame)
            } else {
                let diff = delta(from: lastState!, to: state)
                if diff.count == 0 { return nil }
                if state.count >= keyframeRatioMinNodes
                    && Double(diff.count) >= Double(state.count) * deltaToKeyframeRatio
                {
                    entry = keyframe(frame)
                } else {
                    entry = [
                        "ts": frame.ts,
                        "kind": "delta",
                        "added": diff.added.map { encode($0.node, extra: ["at": $0.at, "id": $0.id]) },
                        "changed": diff.changed.map { encode($0.node, extra: ["id": $0.id]) },
                        "removed": diff.removed.map {
                            ["x": $0.node.x, "y": $0.node.y, "w": $0.node.w, "h": $0.node.h,
                             "id": $0.id] as [String: Any]
                        },
                    ]
                }
            }

            entries.append(entry)
            evict(now: frame.ts)
            lastState = state
            return entry
        }

        func snapshot() -> [[String: Any]] {
            lock.lock()
            defer { lock.unlock() }
            return entries
        }

        /// Hand over the ring and start again cold, so the next frame
        /// is a keyframe. Resuming with a delta would reconstruct
        /// against a state the player no longer holds.
        func drain() -> [[String: Any]] {
            lock.lock()
            defer { lock.unlock() }
            let out = entries
            entries = []
            lastState = nil
            lastKeyframeTs = 0
            return out
        }

        private func keyframe(_ frame: Frame) -> [String: Any] {
            lastKeyframeTs = frame.ts
            return [
                "ts": frame.ts,
                "kind": "key",
                "width": frame.width,
                "height": frame.height,
                "nodes": frame.nodes.map { encode($0, extra: [:]) },
            ]
        }

        private func evict(now: Double) {
            let cutoff = now - windowMs
            while let first = entries.first, (first["ts"] as? Double ?? 0) < cutoff {
                entries.removeFirst()
            }
            while entries.count > maxItems { entries.removeFirst() }
        }
    }

    /// Optional fields are left out rather than sent as null, which is
    /// what `JSON.stringify` does with an absent key — and the player
    /// reads "absent" and "null" the same way only by accident.
    static func encode(_ node: Node, extra: [String: Any]) -> [String: Any] {
        var out: [String: Any] = ["x": node.x, "y": node.y, "w": node.w, "h": node.h]
        if let kind = node.kind { out["kind"] = kind }
        if let text = node.text { out["text"] = text }
        if let color = node.color { out["color"] = color }
        for (key, value) in extra { out[key] = value }
        return out
    }
}
