import CryptoKit
import Foundation

/// Turns a raw identity into the key that travels on the wire.
///
/// Every event carries `userKey`, and a registered device carries the
/// same one — that join is what lets an issue reach the people it
/// happened to. The raw value never leaves the device; only this
/// hash does.
///
/// Three implementations now compute it: TypeScript in
/// `sdk/core/src/identity.ts`, this, and Kotlin. They must agree
/// byte for byte. If they drift, a device stops matching the events
/// from the same person: the push reaches nobody and nothing reports
/// it, which is precisely the failure mode that makes a second
/// implementation a bad idea in the first place.
///
/// So this is not written against the TypeScript, it is tested
/// against it — `sdk/native/fixtures/identity-vectors.json` is
/// generated by that module and asserted here.
///
/// The client hash is unsalted. The server layers its own per-scope
/// salt before storing a fingerprint; several comments in this
/// codebase call the client value "salted", and they are wrong.
@objc(SentoriIdentity)
public final class SentoriIdentity: NSObject {

    /// SHA-256 of the normalised value, lowercase hex. `nil` for an
    /// empty or whitespace-only input — no key beats a meaningless
    /// one, and the caller treats absent as "broadcast only".
    @objc public static func hash(keyType: String, value: String) -> String? {
        let normalised = normalise(keyType: keyType, raw: value)
        if normalised.isEmpty { return nil }
        let digest = SHA256.hash(data: Data(normalised.utf8))
        return digest.map { String(format: "%02x", $0) }.joined()
    }

    /// The key for a user, matching `scope.ts`: the id if there is
    /// one, otherwise the email. Not both — one device, one key.
    @objc public static func userKey(id: String?, email: String?) -> String? {
        if let id, let h = hash(keyType: "id", value: id) { return h }
        if let email, let h = hash(keyType: "email", value: email) { return h }
        return nil
    }

    /// Well-known normalisations, mirroring `normalise` in
    /// `identity.ts`. A type this does not know about gets a plain
    /// trim, which is that function's `default` branch.
    /// What JavaScript's `String.prototype.trim` removes.
    ///
    /// Not `.whitespacesAndNewlines`. That set contains U+00A0 but not
    /// U+FEFF, which Unicode classifies as a format character rather
    /// than whitespace — while ECMAScript's `WhiteSpace` production
    /// lists it explicitly. A value pasted from a web page carries
    /// either, and a device that trimmed differently would stop
    /// matching its own events for that one user.
    ///
    /// Kotlin needs its own version of this for a different reason:
    /// `Character.isWhitespace` excludes both. Three languages, three
    /// definitions of "blank", one value that has to come out the
    /// same.
    private static let trimmed: CharacterSet = {
        var set = CharacterSet.whitespacesAndNewlines
        set.insert(charactersIn: "\u{feff}")
        return set
    }()

    static func normalise(keyType: String, raw: String) -> String {
        switch keyType {
        case "email", "username":
            return raw.trimmingCharacters(in: trimmed).lowercased()
        case "phone":
            // Everything that is not `+` or a digit goes, so
            // "+81 (90) 1234-5678" and "+819012345678" agree. This is
            // deliberately not E.164 validation — that is the host's
            // business; this only removes formatting noise.
            return raw.filter { $0 == "+" || $0.isASCII && $0.isNumber }
        case "googleSub", "appleSub", "metaSub":
            // OAuth subject claims are opaque. Touching them would
            // change an identifier the provider defined.
            return raw
        default:
            return raw.trimmingCharacters(in: trimmed)
        }
    }
}
